name: ericalee
favicon: null
layout_spectrum: 0.8374011765699834
typography_spectrum: 0.7740980677772313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.24634376959875226
  lightness: 0.5481223145034164
  saturation: 0.7002910641022027
  rhythmicContrast: 0.49471188778989017
purpose: []
